version: '3.5'

services:
  postgres:
    container_name: postgis_container
    image: kartoza/postgis:12.0
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=sdla
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    volumes:
       - postgis-data:/var/lib/postgresql
    ports:
      - "5434:5432"
    networks:
      - postgis
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-info@nitech.it}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-nitech.2020}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgis
    restart: unless-stopped

networks:
  postgis:
    driver: bridge

volumes:
    postgis-data:
    pgadmin: