version: '3.5'

services:
  postgres:
    container_name: postgis_container
    image: kartoza/postgis:12.0
    environment:
      POSTGRES_DB:gis_template
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-postgres}
    volumes:
       - postgis-data:/var/lib/postgresql
    ports:
      - "5434:5432"
    networks:
      - postgis
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-info@nitech.it}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-nitech.2020}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgis
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgis-data:
    pgadmin: